[package]
name = "bikemonkey2"
version = "0.1.0"
authors = ["Blake Kaplan <mrbkap@gmail.com>"]

[dependencies]
clap = "~2.32.0"
serde_json = "1.0"
serde = "*"
serde_derive = "*"
caseless = "0.2.0"
regex = "1.1.0"
lazy_static = "1.2.0"
