[package]
name = "bikemonkey2"
version = "0.1.0"
authors = ["Blake Kaplan <mrbkap@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
caseless = "0.2.1"
regex = "1.1.5"
lazy_static = "1.3.0"
